"""SQLAlchemy database models."""
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, ForeignKey, UniqueConstraint
from sqlalchemy.orm import relationship
from datetime import datetime
from .database import Base


class Asset(Base):
    """Stock/asset information."""
    __tablename__ = "assets"

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(20), unique=True, index=True, nullable=False)
    name = Column(String(255))
    sector = Column(String(100))
    industry = Column(String(100))
    market_cap = Column(Float)
    exchange = Column(String(50))
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    prices = relationship("PriceDaily", back_populates="asset", cascade="all, delete-orphan")
    features = relationship("FeatureDaily", back_populates="asset", cascade="all, delete-orphan")


class PriceDaily(Base):
    """Daily price data."""
    __tablename__ = "prices_daily"

    id = Column(Integer, primary_key=True, index=True)
    asset_id = Column(Integer, ForeignKey("assets.id"), nullable=False, index=True)
    time = Column(DateTime, nullable=False, index=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(Float)
    adjusted_close = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    asset = relationship("Asset", back_populates="prices")

    # Ensure one price per asset per day
    __table_args__ = (
        UniqueConstraint('asset_id', 'time', name='uq_asset_time'),
    )


class FeatureDaily(Base):
    """Daily calculated features."""
    __tablename__ = "features_daily"

    id = Column(Integer, primary_key=True, index=True)
    asset_id = Column(Integer, ForeignKey("assets.id"), nullable=False, index=True)
    time = Column(DateTime, nullable=False, index=True)
    feature_name = Column(String(100), nullable=False, index=True)
    value = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    asset = relationship("Asset", back_populates="features")

    # Ensure one feature value per asset per feature per day
    __table_args__ = (
        UniqueConstraint('asset_id', 'time', 'feature_name', name='uq_asset_time_feature'),
    )


class MarketRegime(Base):
    """Market regime classifications."""
    __tablename__ = "market_regimes"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(DateTime, unique=True, nullable=False, index=True)
    regime_label = Column(String(50), nullable=False)  # bull, bear, neutral, etc.
    confidence = Column(Float)
    spy_trend = Column(String(20))
    vix_level = Column(Float)
    breadth_score = Column(Float)
    metrics_json = Column(String)  # JSON string for additional metrics
    created_at = Column(DateTime, default=datetime.utcnow)


class Signal(Base):
    """Trading signals generated by strategies."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    asset_id = Column(Integer, ForeignKey("assets.id"), nullable=False, index=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id"), nullable=False)
    generated_at = Column(DateTime, nullable=False, index=True)
    signal_type = Column(String(20), nullable=False)  # BUY, SELL, HOLD
    score = Column(Float)
    entry_price = Column(Float)
    stop_price = Column(Float)
    target_price = Column(Float)
    model_version = Column(String(50))
    status = Column(String(20), default='PENDING')  # PENDING, ACTIVE, CLOSED, CANCELLED
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    asset = relationship("Asset")
    strategy = relationship("Strategy", back_populates="signals")


class Strategy(Base):
    """Trading strategy definitions."""
    __tablename__ = "strategies"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)
    description = Column(String)
    is_active = Column(Boolean, default=True)
    parameters_json = Column(String)  # JSON string for strategy parameters
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    signals = relationship("Signal", back_populates="strategy")