'use client'

import { FormEvent, useState } from 'react'
import { Gauge, Play, Radio, Target, TrendingUp } from 'lucide-react'
import MetricCard from '@/components/MetricCard'
import PageHeader from '@/components/PageHeader'
import { EmptyState, ErrorState, LoadingState } from '@/components/PanelState'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { api, apiErrorMessage, StockScore } from '@/lib/api'
import { formatCurrency, titleCase } from '@/lib/utils'

export default function ScannerPage() {
  const [tickers, setTickers] = useState('')
  const [topN, setTopN] = useState(20)
  const [results, setResults] = useState<StockScore[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [hasRun, setHasRun] = useState(false)

  async function runScan(event?: FormEvent) {
    event?.preventDefault()
    setLoading(true); setError(''); setHasRun(true)
    try {
      const response = await api.get<StockScore[]>('/api/v1/scanner/scan', { params: { top_n: topN, tickers: tickers || undefined, use_cached_features: false } })
      setResults(response.data)
    } catch (requestError) {
      setResults([]); setError(apiErrorMessage(requestError))
    } finally { setLoading(false) }
  }

  const average = results.length ? results.reduce((sum, item) => sum + item.composite_score, 0) / results.length : 0
  const top = results[0]

  return (
    <main>
      <PageHeader eyebrow="Cross-sectional research" title="Opportunity scanner" description="Rank the recovered provider universe across momentum, breakout quality, relative strength, volume and market compatibility. Results are generated by the project’s deterministic mock provider—not live trade recommendations." actions={<Badge tone="warning">Mock market data</Badge>} />

      <Card className="mt-6"><CardContent className="pt-5"><form onSubmit={runScan} className="grid items-end gap-4 lg:grid-cols-[1fr_150px_auto]"><label><span className="label">Tickers, optional</span><input className="field" value={tickers} onChange={(e) => setTickers(e.target.value.toUpperCase())} placeholder="AAPL, MSFT, NVDA" /></label><label><span className="label">Top results</span><input className="field" type="number" min={1} max={100} value={topN} onChange={(e) => setTopN(Number(e.target.value))} /></label><Button type="submit" disabled={loading}><Play size={15} />{loading ? 'Scanning…' : 'Run scanner'}</Button></form></CardContent></Card>

      <section className="section-grid">
        <MetricCard label="Opportunities" value={String(results.length)} detail="Ranked records" icon={Radio} />
        <MetricCard label="Average score" value={average ? average.toFixed(1) : '—'} detail="Composite score / 100" icon={Gauge} />
        <MetricCard label="Top setup" value={top ? titleCase(top.setup_type) : '—'} detail={top?.ticker || 'Run a scan'} icon={Target} />
        <MetricCard label="Highest score" value={top ? top.composite_score.toFixed(1) : '—'} detail={top ? `${top.confidence} confidence` : 'No result'} icon={TrendingUp} tone={top && top.composite_score >= 70 ? 'positive' : 'default'} />
      </section>

      <Card className="mt-6 overflow-hidden"><CardHeader><CardTitle>Ranked opportunities</CardTitle><CardDescription>Factor components are shown independently so the composite score is auditable.</CardDescription></CardHeader>{loading ? <LoadingState label="Calculating features and ranking the universe" /> : error ? <ErrorState message={error} /> : !hasRun ? <EmptyState title="No scan has been run" detail="Choose an optional ticker list or scan the default recovered mock universe." /> : !results.length ? <EmptyState title="No opportunities passed" detail="Try a broader ticker selection or inspect the API error log." /> : <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Rank</TableHead><TableHead>Symbol</TableHead><TableHead>Price</TableHead><TableHead>Composite</TableHead><TableHead>Momentum</TableHead><TableHead>Breakout</TableHead><TableHead>Relative strength</TableHead><TableHead>Setup</TableHead><TableHead>Confidence</TableHead></TableRow></TableHeader><TableBody>{results.map((stock) => <TableRow key={stock.ticker}><TableCell className="font-mono text-muted-foreground">#{stock.rank}</TableCell><TableCell><p className="font-semibold text-white">{stock.ticker}</p><p className="max-w-36 truncate text-xs text-muted-foreground">{stock.company_name}</p></TableCell><TableCell className="font-mono">{formatCurrency(stock.price)}</TableCell><TableCell className="font-mono font-semibold text-cyan-200">{stock.composite_score.toFixed(1)}</TableCell><TableCell className="font-mono">{stock.momentum_score.toFixed(1)}</TableCell><TableCell className="font-mono">{stock.breakout_score.toFixed(1)}</TableCell><TableCell className="font-mono">{stock.relative_strength_score.toFixed(1)}</TableCell><TableCell><Badge>{titleCase(stock.setup_type)}</Badge></TableCell><TableCell><Badge tone={stock.confidence === 'high' ? 'positive' : stock.confidence === 'medium' ? 'info' : 'neutral'}>{stock.confidence}</Badge></TableCell></TableRow>)}</TableBody></Table></div>}</Card>
    </main>
  )
}
