'use client'

import { useEffect, useState } from 'react'
import { Activity, Gauge, RefreshCw, ShieldAlert, Waves } from 'lucide-react'
import Chart from '@/components/Chart'
import MetricCard from '@/components/MetricCard'
import PageHeader from '@/components/PageHeader'
import { ErrorState, LoadingState } from '@/components/PanelState'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { api, apiErrorMessage, RegimeResponse } from '@/lib/api'
import { titleCase } from '@/lib/utils'

interface RegimeHistoryPoint { date: string; regime: string; risk_score: number; confidence: number }

export default function MarketRegimePage() {
  const [current, setCurrent] = useState<RegimeResponse | null>(null)
  const [history, setHistory] = useState<RegimeHistoryPoint[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  async function load() {
    setLoading(true); setError('')
    try {
      const [currentResponse, historyResponse] = await Promise.all([
        api.get<RegimeResponse>('/api/v1/regime/current'),
        api.get<RegimeHistoryPoint[]>('/api/v1/regime/history', { params: { days: 90 } }),
      ])
      setCurrent(currentResponse.data); setHistory(historyResponse.data)
    } catch (requestError) { setError(apiErrorMessage(requestError)) } finally { setLoading(false) }
  }

  useEffect(() => { load() }, [])

  const riskTone = current && current.risk_score >= 70 ? 'negative' : current && current.risk_score >= 50 ? 'warning' : 'positive'
  return (
    <main>
      <PageHeader eyebrow="Risk context" title="Market regime" description="Translate trend, volatility and breadth into an explicit risk posture and strategy compatibility map. The current recovered endpoint uses default or manually submitted inputs; its history is a deterministic simulation." actions={<><Badge tone="warning">Simulated inputs</Badge><Button variant="secondary" size="sm" onClick={load} disabled={loading}><RefreshCw size={14} />Refresh</Button></>} />
      {loading ? <Card className="mt-6"><LoadingState label="Evaluating market state" /></Card> : error ? <Card className="mt-6"><ErrorState message={error} /></Card> : current && <>
        <section className="section-grid"><MetricCard label="Regime" value={titleCase(current.regime)} detail={`${Math.round(current.confidence * 100)}% confidence`} icon={Activity} /><MetricCard label="Risk score" value={`${current.risk_score.toFixed(0)} / 100`} detail={current.risk_score >= 70 ? 'Capital preservation' : current.risk_score >= 50 ? 'Reduce exposure' : 'Normal positioning'} icon={ShieldAlert} tone={riskTone === 'positive' ? 'positive' : riskTone === 'negative' ? 'negative' : 'default'} /><MetricCard label="Breadth" value={`${current.breadth_score.toFixed(0)} / 100`} detail="Participation score" icon={Gauge} /><MetricCard label="Volatility" value={titleCase(current.volatility_regime)} detail={`VIX state: ${titleCase(current.vix_level)}`} icon={Waves} /></section>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><Card><CardHeader><CardTitle>90-day risk trace</CardTitle><CardDescription>Generated by the recovered deterministic history endpoint; not a live VIX feed.</CardDescription></CardHeader><CardContent><Chart mode="risk" data={history.map((point) => ({ date: point.date, risk: point.risk_score }))} /></CardContent></Card><Card><CardHeader><CardTitle>Strategy compatibility</CardTitle><CardDescription>Guidance produced by the regime detector.</CardDescription></CardHeader><CardContent className="space-y-3">{Object.entries(current.strategy_recommendations).map(([name, value]) => name === 'description' ? <p key={name} className="mt-4 rounded-xl border border-white/5 bg-white/[0.025] p-4 text-sm leading-6 text-muted-foreground">{value}</p> : <div key={name} className="flex items-center justify-between gap-4 border-b border-white/5 pb-3"><span className="text-sm text-slate-300">{titleCase(name)}</span><Badge tone={value === 'favourable' ? 'positive' : value === 'unfavourable' ? 'negative' : 'neutral'}>{value}</Badge></div>)}</CardContent></Card></div>
      </>}
    </main>
  )
}
